In [1]:
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv(r"C:\Users\91755\Downloads\Bank_Personal_Loan_Modelling.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   ID                  5000 non-null   int64  
 1   Age                 5000 non-null   int64  
 2   Experience          5000 non-null   int64  
 3   Income              5000 non-null   int64  
 4   ZIP Code            5000 non-null   int64  
 5   Family              5000 non-null   int64  
 6   CCAvg               5000 non-null   float64
 7   Education           5000 non-null   int64  
 8   Mortgage            5000 non-null   int64  
 9   Personal Loan       5000 non-null   int64  
 10  Securities Account  5000 non-null   int64  
 11  CD Account          5000 non-null   int64  
 12  Online              5000 non-null   int64  
 13  CreditCard          5000 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 547.0 KB


In [4]:
df.head()

ID  Age  Experience  Income  ZIP Code  Family  CCAvg  Education  Mortgage  \
0   1   25           1      49     91107       4    1.6          1         0   
1   2   45          19      34     90089       3    1.5          1         0   
2   3   39          15      11     94720       1    1.0          1         0   
3   4   35           9     100     94112       1    2.7          2         0   
4   5   35           8      45     91330       4    1.0          2         0   

   Personal Loan  Securities Account  CD Account  Online  CreditCard  
0              0                   1           0       0           0  
1              0                   1           0       0           0  
2              0                   0           0       0           0  
3              0                   0           0       0           0  
4              0                   0           0       0           1

In [5]:
df = df.drop(['ID'],axis=1)

In [6]:
x = df.drop(['Personal Loan'],axis=1).values

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-1.77441684, -1.66607847, -0.53822878, ..., -0.25354028,
        -1.21661774, -0.64531434],
       [-0.02952359, -0.09633022, -0.8641094 , ..., -0.25354028,
        -1.21661774, -0.64531434],
       [-0.55299157, -0.44516316, -1.36379301, ..., -0.25354028,
        -1.21661774, -0.64531434],
       ...,
       [ 1.54088033,  1.64783451, -1.08136314, ..., -0.25354028,
        -1.21661774, -0.64531434],
       [ 1.71536965,  1.73504275, -0.53822878, ..., -0.25354028,
         0.82195086, -0.64531434],
       [-1.51268285, -1.40445376,  0.20043396, ..., -0.25354028,
         0.82195086,  1.54963239]])

In [8]:
from sklearn.model_selection import train_test_split
y = df['Personal Loan'].values 
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=10,test_size=0.3)

In [9]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(3500, 12)
(3500,)
(1500, 12)
(1500,)


In [10]:
import tensorflow as tf 

In [11]:
tf.random.set_seed(40)
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=[12]))
model.add(tf.keras.layers.Dense(8,activation='relu'))
model.add(tf.keras.layers.Dense(4,activation='relu'))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 104       
                                                                 
 dense_1 (Dense)             (None, 4)                 36        
                                                                 
 dense_2 (Dense)             (None, 1)                 5         
                                                                 
Total params: 145
Trainable params: 145
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.compile(loss='BinaryCrossentropy',optimizer='sgd',metrics=['accuracy'])

In [14]:
history = model.fit(x_train,y_train,epochs=50)

Epoch 1/50
110/110 [==============================] - 2s 4ms/step - loss: 0.5823 - accuracy: 0.8049
Epoch 2/50
110/110 [==============================] - 0s 4ms/step - loss: 0.4282 - accuracy: 0.9023
Epoch 3/50
110/110 [==============================] - 0s 4ms/step - loss: 0.3675 - accuracy: 0.9023
Epoch 4/50
110/110 [==============================] - 0s 3ms/step - loss: 0.3361 - accuracy: 0.9023
Epoch 5/50
110/110 [==============================] - 0s 3ms/step - loss: 0.3158 - accuracy: 0.9023
Epoch 6/50
110/110 [==============================] - 0s 4ms/step - loss: 0.2992 - accuracy: 0.9023
Epoch 7/50
110/110 [==============================] - 0s 4ms/step - loss: 0.2848 - accuracy: 0.9029
Epoch 8/50
110/110 [==============================] - 0s 4ms/step - loss: 0.2719 - accuracy: 0.9034
Epoch 9/50
110/110 [==============================] - 0s 4ms/step - loss: 0.2597 - accuracy: 0.9054
Epoch 10/50
110/110 [==============================] - 0s 4ms/step - loss: 0.2482 - accuracy: 0.9060

In [15]:
model.evaluate(x_test,y_test)

47/47 [==============================] - 0s 3ms/step - loss: 0.0923 - accuracy: 0.9693


[0.09233666956424713, 0.9693333506584167]

In [16]:
pred = model.predict(x_test)

47/47 [==============================] - 0s 3ms/step


In [17]:
y_pred = pred > 0.5 
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [18]:
from sklearn.preprocessing import LabelEncoder 
l = LabelEncoder()
y_pred = l.fit_transform(y_pred.flatten())

In [19]:
y_pred 

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [20]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_test,y_pred)

0.9693333333333334

## PyTorch

In [44]:
import torch 
import numpy as np

In [45]:
torch.set_default_dtype(torch.float64)

In [46]:
x_train2 = np.array(x_train)
x_train2 = torch.from_numpy(x_train2)
x_train2 = x_train2.double()

In [47]:
y_train2 = np.array(y_train)
y_train2 = torch.from_numpy(y_train2)
y_train2 = y_train2.double()

In [48]:
from torch.utils.data import TensorDataset 
from torch.utils.data import DataLoader 
from torch import nn

In [49]:
tr = TensorDataset(x_train2,y_train2)

In [50]:
tr[0]

(tensor([ 1.1047,  1.2118,  0.1353, -1.4411, -0.3454, -0.1934, -1.0491, -0.5555,
         -0.3414, -0.2535,  0.8220,  1.5496]),
 tensor(0.))

In [51]:
x_train_dl = DataLoader(tr,batch_size=10,shuffle=True)

In [52]:
class NN(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(12,10),
            nn.ReLU(),
            nn.Linear(10,5),
            nn.Sigmoid(),
            nn.Linear(5,1)
        )
    def forward(self,x):
        logits = self.linear_relu_stack(x) 
        return logits

In [53]:
m = NN()
m

NN(
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=12, out_features=10, bias=True)
    (1): ReLU()
    (2): Linear(in_features=10, out_features=5, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=5, out_features=1, bias=True)
  )
)

In [55]:
pr = model(x_train)

In [32]:
pred = pr > 0.5 

In [33]:
lc = LabelEncoder()
pred = lc.fit_transform(pred)

C:\Users\91755\AppData\Roaming\Python\Python39\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [34]:
pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [35]:
accuracy_score(y_train,pred)

0.97

In [36]:
loss = nn.MSELoss()

In [37]:
optim = torch.optim.SGD(m.parameters(),lr=0.01)

In [38]:
def train(m,ep,d):
    for i in range(ep):
        for a,b in d: 
            pr = m(a)
            b = b.unsqueeze(0)
            l = loss(pr,b)
            l.backward()
            optim.step()
            optim.zero_grad()
            if i % 10 == 0:
                print(f"Epoch: {i+1}, Error: {l}")

In [39]:
train(m,50,tr)

Epoch: 1, Error: 0.11584724982732397
Epoch: 1, Error: 0.10050889517670634
Epoch: 1, Error: 0.16476722264284785
Epoch: 1, Error: 0.06477919891156213
Epoch: 1, Error: 0.0382320775132209
Epoch: 1, Error: 0.11285294015756352
Epoch: 1, Error: 0.07620286703396267
Epoch: 1, Error: 0.03064712926825474
Epoch: 1, Error: 0.02903780164932491
Epoch: 1, Error: 0.03805651024849816
Epoch: 1, Error: 0.019671533595751394
Epoch: 1, Error: 0.027716903553601412
Epoch: 1, Error: 1.3228757693083246
Epoch: 1, Error: 0.012410830297092012
Epoch: 1, Error: 0.008580864929123563
Epoch: 1, Error: 0.010884413093329316
Epoch: 1, Error: 1.207526729377981
Epoch: 1, Error: 0.0008436657998653513
Epoch: 1, Error: 0.005652215728171248
Epoch: 1, Error: 0.00022333768142740782
Epoch: 1, Error: 0.00034876455625245626
Epoch: 1, Error: 0.0037397380289739004
Epoch: 1, Error: 0.012000194998150457
Epoch: 1, Error: 2.1639637063977784e-05
Epoch: 1, Error: 0.974802149232763
Epoch: 1, Error: 0.00031203560850079744
Epoch: 1, Error: 9.65

In [40]:
pred = m(torch.from_numpy(x_test))

In [41]:
pred = pred > 0.5 

In [42]:
pred = lc.fit_transform(pred.flatten())

In [43]:
accuracy_score(y_test,pred)

0.978